fix: resolved npm audit and sonarqube issues
contentstack/datasync-asset-store-filesystem pull request #5
Opened 2022-09-19 17:39 UTC by vkalta

2022-09-21 05:25 UTC, netrajpatel approved these changes

2022-09-21 05:35 UTC, vkaltae9 commented on package.json
>      "debug": "4.1.1",
@netrajpatel It is added. You are seeing the outdated version.

2022-10-28 12:49 UTC, netrajpatel requested changes
@vkalta Update package versions

2022-10-28 15:49 UTC, aravindbuilt approved these changes

2022-10-30 20:43 UTC, vkalta commented
> @vkalta Update package versions

@netrajpatel Done.

2022-10-31 05:07 UTC, netrajpatel approved these changes

2022-10-31 10:18 UTC, netrajpatel approved these changes

2022-10-31 10:19 UTC, netrajpatel approved these changes

2022-10-31 12:58 UTC, merged